### PR TITLE
Replace travis with github actions

### PR DESCRIPTION
**Pull request by luca-rath**

### CODE REVIEW

**Comment by luca-rath** [comment]
@alexander-schranz Do you have an idea why the `php7.2` job is failing?

**Comment by alexander-schranz** [comment]
@luca-rath did check the dependencies with the last travis run which did work without problems. The normal dependencies are still the same. The phpunit dependencies did change prophecy 1.12.1 -> 1.12.2 and the release maybe did break something for us: https://github.com/phpspec/prophecy/releases. But strange that this only happens on PHP 7.2 🤔.

**Comment by alexander-schranz** [comment]
Can you reproduce the error locally?

**Comment by luca-rath** [comment]
> Can you reproduce the error locally?

Yes, this also happens on my local environment

> @luca-rath did check the dependencies with the last travis run which did work without problems. The normal dependencies are still the same. The phpunit dependencies did change prophecy 1.12.1 -> 1.12.2 and the release maybe did break something for us: https://github.com/phpspec/prophecy/releases. But strange that this only happens on PHP 7.2 🤔.

This doesn't look like an issue with prophecy.
It seems the problem is that `$collection->get('cget_media')` returns `null`.

**Comment by luca-rath** [comment]
https://github.com/handcraftedinthealps/RestRoutingBundle/blob/master/Tests/Routing/Loader/RestRouteLoaderTest.php#L332 This is the corresponding line

**Comment by luca-rath** [comment]
The generated routes are `get_media` and `get_medias` instead of the expected `get_media` and `cget_media`

**Comment by alexander-schranz** [comment]
@luca-rath this seems like a composer issue installing 2.8.0-beta1 instead of 2.8.0 on `prefer-stable` in combination with minimum-stability dev. We currently can workaround this  issue by checking running: 

```
composer config minimum-stability stable
```

for the `--prefer-lowest` tests. 

Currently I would comment `8.1` out as prophecy does not yet support php 8.1 yet and fails and this will currently just misslead devs creating PR.

**Comment by luca-rath** [comment]
@alexander-schranz why would you run `composer config minimum-stability stable` not for all jobs?

**Comment by alexander-schranz** [comment]
@luca-rath because I want to test against newest dependencies to get errors as soon as possible and not after they got released.

**Pull request closed without merging**
